image: maven:3.6-jdk-8-alpine
# Inspired by https://gitlab.com/gitlab-examples/maven/simple-maven-dep and
# https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml
# 
# Signing procedure inspired by https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/922/diffs
# and related code.
#
# run manually with `gitlab-runner exec docker <task_name>`

variables:
  BUILD_NUMBER: ${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used

  MAVEN_CLI_OPTS: "--errors --batch-mode --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .m2/repository

# before every job - unless overridden in a stage.
#
# Protected environment variables are only available on protected
# branches and tags. Master is protected by default.
#
before_script:
  - apk update && apk add rsync

validate:
  stage: build
  script:
    - mvn clean
    - mvn $MAVEN_CLI_OPTS test-compile -Dbuild.number=${BUILD_NUMBER}

test:verify:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS verify -Dbuild.number=${BUILD_NUMBER}
  artifacts:
    paths:
      - target/rpki-validator-${BUILD_NUMBER}.jar

snapshot:deploy:
  stage: deploy
  script:
    # this is to be filled in
  only:
    - master